In [1]:
# import libraries needed 
import pandas as pd 
import datetime
from datetime import timedelta
import seaborn as sns 
import networkx as nx
import numpy as np
import community
from IPython.display import Image
import matplotlib
from tqdm import tqdm

In [50]:
# read the raw data 


for m in (range(12,13)):
    base_str = 'C:\\Users\\raosa\\Dropbox\\data\\combined\\'
    data = pd.read_csv('C:\\Users\\raosa\\Dropbox\\dl-graph\\data\\eth\\pricing\\final.csv')
    data['Date'] = pd.to_datetime(data['Date'])
    x=pd.read_csv(str(base_str+str(m)+'.csv'))
    print('reading done')
    print(len(x))
    timestamp_list = x['timestamp']
    value_list = x['value']

    timestamp_list_1=[]
    value_list_1=[]
    print('transaction loop starting')
    for i in  range(0,len(timestamp_list)):
        test1 = datetime.datetime.fromtimestamp(int(str(timestamp_list[i]),16))
        test2 = (int(x['value'][i],16))/1000000000000000000
        timestamp_list_1.append(test1)
        value_list_1.append(test2)
    print('transaction loop done')
    x['timestamp1'] = timestamp_list_1
    x['value1'] = value_list_1


    x=x.drop(['timestamp','value'],axis=1)
    x = x.rename(columns={'timestamp1': 'timestamp', 'value1': 'value'})

    x['timestamp'] = pd.to_datetime(x['timestamp'])







    tran = {}
    for i in (range(0,len(data))):

        time_start = data['Date'][i]
        time_end = data['Date'][i] + timedelta(hours=1)

        hour_tranlist = x[(x['timestamp'] > time_start) & (x['timestamp'] < time_end)]
        hour_tranlist= hour_tranlist.reset_index()

        list1 = hour_tranlist['from']
        list2 = hour_tranlist['to']
        nodes = list(set(list1 + list2))
        G = nx.Graph()
        G.add_nodes_from(nodes)
        G.add_edges_from(list(zip(list1,list2)),weight=x['value'])

        # remove edge less nodes 
        wow = list(G.nodes.data())
        
        wow1 = []

        for j in (range(0,len(wow))):
            if(len(wow)!=0):
                wow1.append(len(nx.edges(G, [str(wow[j][0])])))
            else:
                wow1.append(0)
        if(len(wow1)!=0):

            appending1 = (np.bincount(np.array(wow1)))
            tran[i] = pd.DataFrame({data['Date'][i]: appending1})

#     dataframe1 = pd.concat([tran[i] for i in range(list(tran.keys())[0],list(tran.keys())[len(list(tran.keys())) - 1])], axis=1).transpose()
#     dataframe1.to_csv(str(str(m)+'features.csv'))
    
#     print(m)
#     print('________________________________________________')

reading done
520710
transaction loop starting
transaction loop done
[]

In [49]:
# dataframe1 = pd.concat([tran[i] for i in range(list(tran.keys())[0],list(tran.keys())[len(list(tran.keys())) - 1])], axis=1).transpose()

dict_keys([4480, 4481, 4482, 4483, 4484, 4485, 4486, 4487, 4488, 4489, 4490, 4491, 4492, 4493, 4494, 4495, 4496, 4497, 4498, 4499, 4500, 4501, 4502, 4503, 4504, 4505, 4506, 4507, 4508, 4509, 4510, 4511, 4512, 4513, 4514, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4523, 4524, 4525, 4526, 4527, 4528, 4529, 4530, 4531, 4532, 4533, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541, 4542, 4543, 4544, 4545, 4546, 4547, 4548, 4549, 4550, 4551, 4552, 4553, 4554, 4555, 4556, 4557, 4558, 4559, 4560, 4561, 4562, 4563, 4564, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4572, 4573, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4582, 4583, 4584, 4585, 4586, 4587, 4588, 4589, 4590, 4591, 4592, 4593, 4594, 4595, 4596, 4597, 4598, 4599, 4600, 4601, 4602, 4603, 4604, 4605, 4606, 4607, 4608, 4609, 4610, 4611, 4612, 4613, 4614, 4615, 4616, 4617, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4625, 4626, 4627, 4628, 4629, 4630, 4631, 4632, 4633, 4634, 4635, 4636, 4637, 4638, 4639, 4640, 4641, 4642, 4643, 4644, 4645, 4646, 4647, 4648, 4649, 4650, 4651, 4652, 4653, 4654, 4655, 4656, 4657, 4658, 4659, 4660, 4661, 4662, 4663, 4664, 4665, 4666, 4667, 4668, 4669, 4670, 4671, 4672, 4673, 4674, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 4683, 4684, 4685, 4686, 4687, 4688, 4689, 4690, 4691, 4692, 4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809, 4810, 4811, 4812, 4813, 4814, 4815, 4816, 4817, 4818, 4819, 4820, 4821, 4822, 4823, 4824, 4825, 4826, 4827, 4828, 4829, 4830, 4831, 4832, 4833, 4834, 4835, 4836, 4837, 4838, 4839, 4840, 4841, 4842, 4843, 4844, 4845, 4846, 4847, 4848, 4849, 4850, 4851, 4852, 4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860, 4861, 4862, 4863, 4864, 4865, 4866, 4867, 4868, 4869, 4870, 4871, 4872, 4873, 4874, 4875, 4876, 4877, 4878, 4879, 4880, 4881, 4882, 4883, 4884, 4885, 4886, 4887, 4888, 4889, 4890, 4891, 4892, 4893, 4894, 4895, 4896, 4897, 4898, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918])

In [45]:
pd.DataFrame([ x.split() for x in test63[0].tolist()])

AttributeError: 'DataFrame' object has no attribute 'split'

In [4]:
# # minutes 
# time_start = hour_tranlist['timestamp'][3]
# time_end = hour_tranlist['timestamp'][3] + timedelta(minutes=1)

# hour_tranlist_1 = hour_tranlist[(hour_tranlist['timestamp'] > time_start) & (hour_tranlist['timestamp'] < time_end)]

,0,1,2,3,4,5,6,7,8,9,...,13048,13049,13050,13051,13052,13053,13054,13055,13056,13057
2017-11-06 02:00:00,4859.0,4007.0,658.0,106.0,37.0,38.0,17.0,11.0,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 03:00:00,11561.0,7858.0,2018.0,248.0,80.0,154.0,53.0,22.0,10.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 04:00:00,10510.0,6526.0,2155.0,255.0,76.0,191.0,56.0,17.0,12.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 05:00:00,14473.0,8900.0,2736.0,288.0,102.0,238.0,73.0,34.0,30.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 06:00:00,12517.0,7369.0,2648.0,293.0,103.0,232.0,61.0,34.0,32.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 07:00:00,12044.0,6727.0,2749.0,307.0,109.0,280.0,62.0,24.0,17.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 08:00:00,12133.0,6768.0,2861.0,326.0,83.0,255.0,75.0,45.0,17.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 09:00:00,12178.0,6449.0,2887.0,328.0,109.0,268.0,95.0,27.0,13.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 10:00:00,13734.0,6497.0,3665.0,330.0,111.0,342.0,79.0,30.0,22.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 11:00:00,12213.0,6243.0,2909.0,315.0,109.0,402.0,55.0,18.0,13.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 12:00:00,11208.0,5576.0,2676.0,279.0,124.0,443.0,63.0,30.0,14.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 13:00:00,10977.0,5815.0,2455.0,249.0,97.0,400.0,75.0,25.0,15.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 14:00:00,12882.0,7288.0,2681.0,306.0,96.0,412.0,61.0,20.0,12.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 15:00:00,16535.0,9048.0,3581.0,297.0,87.0,295.0,152.0,28.0,21.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 16:00:00,11020.0,6212.0,2209.0,291.0,76.0,453.0,37.0,23.0,17.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 17:00:00,9930.0,5399.0,2036.0,270.0,144.0,321.0,99.0,24.0,15.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 18:00:00,9913.0,5200.0,2163.0,280.0,106.0,320.0,80.0,15.0,15.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 19:00:00,13159.0,7395.0,2662.0,238.0,97.0,337.0,79.0,19.0,20.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 20:00:00,8711.0,4699.0,1976.0,220.0,72.0,283.0,58.0,11.0,19.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 21:00:00,11286.0,6514.0,2290.0,272.0,89.0,307.0,72.0,24.0,15.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-06 22:00:00,25677.0,19061.0,3176.0,250.0,88.0,334.0,69.0,14.0,17.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2017-11-06 23:00:00,9405.0,5230.0,2055.0,265.0,96.0,253.0,53.0,16.0,13.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 00:00:00,9027.0,5059.0,1976.0,253.0,71.0,250.0,53.0,19.0,18.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 01:00:00,10206.0,6088.0,2075.0,242.0,95.0,215.0,47.0,19.0,17.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 02:00:00,15198.0,10408.0,2453.0,248.0,85.0,191.0,58.0,20.0,17.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 03:00:00,10468.0,6206.0,2107.0,294.0,93.0,202.0,72.0,18.0,13.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 04:00:00,11153.0,6637.0,2346.0,281.0,84.0,224.0,48.0,24.0,9.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 05:00:00,10869.0,6561.0,2228.0,296.0,99.0,210.0,42.0,22.0,13.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 06:00:00,12545.0,7779.0,2513.0,262.0,83.0,203.0,69.0,25.0,20.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 07:00:00,11704.0,6695.0,2617.0,342.0,97.0,213.0,68.0,21.0,13.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 08:00:00,12351.0,7049.0,2746.0,323.0,120.0,301.0,60.0,28.0,16.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 09:00:00,13293.0,7637.0,2883.0,390.0,114.0,357.0,56.0,20.0,21.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 10:00:00,12638.0,6767.0,2905.0,384.0,109.0,353.0,110.0,25.0,16.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 11:00:00,12540.0,6546.0,2940.0,360.0,152.0,309.0,107.0,25.0,15.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 12:00:00,12064.0,5912.0,3040.0,305.0,108.0,382.0,80.0,26.0,16.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 13:00:00,11489.0,5567.0,2777.0,305.0,92.0,419.0,91.0,32.0,17.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 14:00:00,11477.0,6197.0,2517.0,303.0,90.0,398.0,82.0,18.0,16.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 15:00:00,12579.0,7259.0,2495.0,298.0,110.0,427.0,88.0,18.0,12.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 16:00:00,14045.0,7611.0,2959.0,349.0,95.0,360.0,113.0,28.0,14.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 17:00:00,10001.0,5017.0,2242.0,304.0,102.0,435.0,72.0,21.0,10.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 18:00:00,9561.0,5030.0,2095.0,270.0,72.0,330.0,102.0,16.0,20.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 19:00:00,10416.0,5846.0,2107.0,260.0,79.0,369.0,73.0,14.0,14.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 20:00:00,11410.0,6359.0,2314.0,267.0,91.0,363.0,74.0,24.0,8.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 21:00:00,10842.0,6264.0,2189.0,266.0,93.0,329.0,65.0,24.0,15.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-07 22:00:00,10276.0,5380.0,2327.0,286.0,85.0,324.0,98.0,10.0,16.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
appending1 = []
appending1 = (np.bincount(np.array(wow1)))


appending2 = []
appending2 = (np.bincount(np.array(wow2)))

In [53]:

df1 = pd.DataFrame({data['Date'][19200]: appending1})
df2 = pd.DataFrame({data['Date'][19201]: appending2})
df3 = pd.concat([df1,df2], axis=1).transpose()
# df3 = df3.transpose()
df3

,0,1,2,3,4,5,6,7,8,9,...,943,944,945,946,947,948,949,950,951,952
2017-11-08 00:00:00,0.0,6235.0,2245.0,338.0,101.0,272.0,55.0,21.0,19.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2017-11-08 01:00:00,0.0,6461.0,2165.0,305.0,89.0,223.0,71.0,22.0,16.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

19200
19201
19202
19203
19204
19205
19206
19207
19208
19209
19210
19211
19212
19213
19214
19215
19216
19217
19218
19219
19220
19221
19222
19223
19224
19225
19226
19227
19228
19229
19230
19231
19232
19233
19234
19235
19236
19237
19238
19239
19240
19241
19242
19243
19244
19245
19246
19247
19248
19249
19250
19251
19252
19253
19254
19255
19256
19257
19258
19259
19260
19261
19262
19263
19264
19265
19266
19267
19268
19269
19270
19271
19272
19273
19274
19275
19276
19277
19278
19279
19280
19281
19282
19283
19284
19285
19286
19287
19288
19289
19290
19291
19292
19293
19294
19295
19296
19297
19298
19299

In [ ]:
hour_tranlist['timestamp'] = pd.to_datetime(hour_tranlist['timestamp'])